#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_MAX_TRACKS 32U
#define APP_TRACK_NAME_LENGTH 64U
#define APP_MAX_LYRIC_LINES 48U
#define APP_LYRIC_TEXT_LENGTH 48U
#define APP_METADATA_TEXT_LENGTH 64U
#define APP_LRC_READ_LINE_LENGTH 96U
#define APP_LYRIC_END_GRACE_MS 3000U

#define APP_MP3_EXTENSION ".mp3"
#define APP_LRC_EXTENSION ".lrc"

#endif
